package com.tuktuk.pojo;
// Generated Feb 14, 2020 8:49:07 PM by Hibernate Tools 4.3.1



/**
 * Payment generated by hbm2java
 */
public class Payment  implements java.io.Serializable {


     private Integer idpayment;
     private User user;
     private Vehicle vehicle;
     private String date;
     private String time;
     private Double cash;
     private Integer status;
     private Integer payble;
     private Double balance;
     private String paymentDate;
     private String paymentTime;

    public Payment() {
    }

	
    public Payment(Vehicle vehicle) {
        this.vehicle = vehicle;
    }
    public Payment(User user, Vehicle vehicle, String date, String time, Double cash, Integer status, Integer payble, Double balance, String paymentDate, String paymentTime) {
       this.user = user;
       this.vehicle = vehicle;
       this.date = date;
       this.time = time;
       this.cash = cash;
       this.status = status;
       this.payble = payble;
       this.balance = balance;
       this.paymentDate = paymentDate;
       this.paymentTime = paymentTime;
    }
   
    public Integer getIdpayment() {
        return this.idpayment;
    }
    
    public void setIdpayment(Integer idpayment) {
        this.idpayment = idpayment;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Vehicle getVehicle() {
        return this.vehicle;
    }
    
    public void setVehicle(Vehicle vehicle) {
        this.vehicle = vehicle;
    }
    public String getDate() {
        return this.date;
    }
    
    public void setDate(String date) {
        this.date = date;
    }
    public String getTime() {
        return this.time;
    }
    
    public void setTime(String time) {
        this.time = time;
    }
    public Double getCash() {
        return this.cash;
    }
    
    public void setCash(Double cash) {
        this.cash = cash;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }
    public Integer getPayble() {
        return this.payble;
    }
    
    public void setPayble(Integer payble) {
        this.payble = payble;
    }
    public Double getBalance() {
        return this.balance;
    }
    
    public void setBalance(Double balance) {
        this.balance = balance;
    }
    public String getPaymentDate() {
        return this.paymentDate;
    }
    
    public void setPaymentDate(String paymentDate) {
        this.paymentDate = paymentDate;
    }
    public String getPaymentTime() {
        return this.paymentTime;
    }
    
    public void setPaymentTime(String paymentTime) {
        this.paymentTime = paymentTime;
    }




}


