package com.tuktuk.pojo;
// Generated Feb 14, 2020 8:49:07 PM by Hibernate Tools 4.3.1



/**
 * Printinfo generated by hbm2java
 */
public class Printinfo  implements java.io.Serializable {


     private Integer id;
     private String description;

    public Printinfo() {
    }

    public Printinfo(String description) {
       this.description = description;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }




}


