package com.tuktuk.pojo;
// Generated Feb 14, 2020 8:49:07 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Vehicle generated by hbm2java
 */
public class Vehicle  implements java.io.Serializable {


     private Integer idvehicle;
     private String qrid;
     private String vehNo;
     private String ownerName;
     private String mobile1;
     private String mobile2;
     private String address;
     private Integer status;
     private String date;
     private String time;
     private Set payments = new HashSet(0);

    public Vehicle() {
    }

    public Vehicle(String qrid, String vehNo, String ownerName, String mobile1, String mobile2, String address, Integer status, String date, String time, Set payments) {
       this.qrid = qrid;
       this.vehNo = vehNo;
       this.ownerName = ownerName;
       this.mobile1 = mobile1;
       this.mobile2 = mobile2;
       this.address = address;
       this.status = status;
       this.date = date;
       this.time = time;
       this.payments = payments;
    }
   
    public Integer getIdvehicle() {
        return this.idvehicle;
    }
    
    public void setIdvehicle(Integer idvehicle) {
        this.idvehicle = idvehicle;
    }
    public String getQrid() {
        return this.qrid;
    }
    
    public void setQrid(String qrid) {
        this.qrid = qrid;
    }
    public String getVehNo() {
        return this.vehNo;
    }
    
    public void setVehNo(String vehNo) {
        this.vehNo = vehNo;
    }
    public String getOwnerName() {
        return this.ownerName;
    }
    
    public void setOwnerName(String ownerName) {
        this.ownerName = ownerName;
    }
    public String getMobile1() {
        return this.mobile1;
    }
    
    public void setMobile1(String mobile1) {
        this.mobile1 = mobile1;
    }
    public String getMobile2() {
        return this.mobile2;
    }
    
    public void setMobile2(String mobile2) {
        this.mobile2 = mobile2;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }
    public String getDate() {
        return this.date;
    }
    
    public void setDate(String date) {
        this.date = date;
    }
    public String getTime() {
        return this.time;
    }
    
    public void setTime(String time) {
        this.time = time;
    }
    public Set getPayments() {
        return this.payments;
    }
    
    public void setPayments(Set payments) {
        this.payments = payments;
    }




}


